# This workflow installs the package and runs a command with a variety of Python versions

name: Test Python Package Installation

on:
  workflow_dispatch:

jobs:
  test-installation:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, macos-13, macos-14, macos-15, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install .
          
    - name: Run command
      run: clem list backends
